name: Terraform Plan
on: push
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
  ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  TF_VAR_aws_pub_key: ${{secrets.AWS_PUBLIC_KEY}}
  TF_VAR_azure_pub_key: ${{secrets.AZURE_PUBLIC_KEY}}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Terraform Init
      working-directory: /home/runner/work/terraform-project/pipeline-github-actions/
      run: terraform init

    - name: Terraform Fmt
      working-directory: /home/runner/work/terraform-project/pipeline-github-actions/
      run: terraform fmt -check

    - name: Terraform Validate
      working-directory: /home/runner/work/terraform-project/pipeline-github-actions/
      run: terraform validate

    - name: Terraform Plan
      working-directory: /home/runner/work/terraform-project/pipeline-github-actions/
      run: terraform plan
